//! `SeaORM` Entity. Generated by sea-orm-codegen 0.12.14

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(table_name = "mod_hash")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i32,
    pub mod_id: i32,
    pub file: String,
    #[sea_orm(unique)]
    pub hash: String,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::sims_mod::Entity",
        from = "Column::ModId",
        to = "super::sims_mod::Column::Id",
        on_update = "NoAction",
        on_delete = "Cascade"
    )]
    SimsMod,
}

impl Related<super::sims_mod::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::SimsMod.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
