//! `SeaORM` Entity. Generated by sea-orm-codegen 0.12.14

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(table_name = "mod_tag_relation")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub mod_id: i32,
    #[sea_orm(primary_key, auto_increment = false)]
    pub tag_id: i32,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::sims_mod::Entity",
        from = "Column::ModId",
        to = "super::sims_mod::Column::Id",
        on_update = "NoAction",
        on_delete = "Cascade"
    )]
    SimsMod,
    #[sea_orm(
        belongs_to = "super::tag::Entity",
        from = "Column::TagId",
        to = "super::tag::Column::Id",
        on_update = "NoAction",
        on_delete = "Cascade"
    )]
    Tag,
}

impl Related<super::sims_mod::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::SimsMod.def()
    }
}

impl Related<super::tag::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Tag.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
