//! `SeaORM` Entity. Generated by sea-orm-codegen 0.12.14

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(table_name = "tag")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i32,
    #[sea_orm(unique)]
    pub tag: String,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(has_many = "super::mod_tag_relation::Entity")]
    ModTagRelation,
}

impl Related<super::mod_tag_relation::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::ModTagRelation.def()
    }
}

impl Related<super::sims_mod::Entity> for Entity {
    fn to() -> RelationDef {
        super::mod_tag_relation::Relation::SimsMod.def()
    }

    fn via() -> Option<RelationDef> {
        Some(super::mod_tag_relation::Relation::Tag.def().rev())
    }
}

impl ActiveModelBehavior for ActiveModel {}
